# Generated by Django 2.2.14 on 2021-07-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invsystest', '0002_order_order_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_cost',
            field=models.IntegerField(null=True),
        ),
    ]
