# Generated by Django 2.2.14 on 2021-07-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invsystest', '0004_auto_20210728_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
