# Generated by Django 2.2.14 on 2021-07-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invsystest', '0006_auto_20210728_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_name',
        ),
        migrations.AddField(
            model_name='order',
            name='order_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_quantity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
