# Generated by Django 2.2.14 on 2021-07-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invsystest', '0008_auto_20210730_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_seller',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
